### ISSUE TITLE
How to Control Network Use of the Toolbox better in Java?

### ISSUE THREAD

**Issue by sami10007** [ikarosilva/wfdb-app-toolbox#120]
Dear Silva, 

I need to better control the network access in/out of the toolbox because of various reasons. I need logs about what the toolbox is doing. I can do this in Java, which you are using in some parts. Thread about the issue as case here http://stackoverflow.com/q/36850459/54964 I think then a getter could be made in Matlab to call Java to get the logs etc during the execution.  

How can you control better the network use of the toolbox?

**Comment by ikarosilva** [comment]
Hi,

The cleanest way to do this would be setting your WFDBPATH so that the toolbox searches your local directory first (default) and then either a PhysioNet server (any of the mirrors) or none at all.

You can change that variable at:

https://github.com/ikarosilva/wfdb-app-toolbox/blob/master/mcode/wfdbloadlib.m

See lines 45-50:

%WFDB_PATH: If empty, will use the default given config.WFDB_PATH
%this is where the toolbox searches  for data files (*.dat, *.hea etc).
%When unistalling the toolbox, you may wish to clear this directory to save space.
%See http://www.physionet.org/physiotools/wag/setwfd-1.htm for more details.
WFDB_PATH=[];

**Comment by sami10007** [comment]
Do you mean to just initiate `WFDB_PATH=['/Users/masi/Databases'];` before calling `rdsamp(...)` or to edit the file wfdbloadlib.m in my local system where to make the change? 

It would be nice not to edit your files directly of the system such that I can easily upgrade the system when you push a new system.
